import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Container!</h1>
        <div>
          <Link href="/app1">Go to App1</Link>
          <Link href="/app2">Go to App2</Link>
        </div>
      </main>
    </div>
  );
}
